//! The serving route is query-local. Model fallback never rewrites user settings.
use lingxi_core::host::{parse_model_ref, ModelListing};
use regex::Regex;
use std::sync::OnceLock;

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ModelRoute {
    pub model: String,
    pub profile: Option<String>,
}

/// Session route transition from one admitted server fallback hop. `from` is
/// the route currently being served; `restore` retains the first route in a
/// live server-owned multi-hop latch.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ServerFallbackTransition {
    pub from: ModelRoute,
    pub to: ModelRoute,
    pub restore: ModelRoute,
}

/// Render the native `sHo` notice from the already-resolved model labels and
/// UI facts. Model lookup, per-model copy selection, and feedback URL selection
/// are kept at the call site so those dependencies are explicit and testable.
pub(crate) struct ServerFallbackNoticeFacts<'a> {
    /// Already-resolved native `Fo(model)` display label.
    pub from_label: &'a str,
    /// Already-resolved native `Fo(model)` display label.
    pub to_label: &'a str,
    /// Raw API refusal category; `k1e` sanitization is applied before display.
    pub category: Option<&'a str>,
    pub scope: lingxi_core::host::refusal_server_control::BannerScope,
    pub retained_text: &'a str,
    /// Snapshot of native `QA()` / `Hre('/feedback')` for this notice.
    pub feedback_available: bool,
    /// Already-resolved native help URL for the original model.
    pub learn_more_url: &'a str,
    /// Full native `R1e` first-time prefix after its settings/trait gates.
    pub first_time_prefix: Option<&'a str>,
    /// Full native `T$r` replacement for the generic switched-to sentence
    /// after its model-trait gates.
    pub switched_to_line: Option<&'a str>,
}

pub(crate) fn server_fallback_notice_text(facts: ServerFallbackNoticeFacts<'_>) -> String {
    let ServerFallbackNoticeFacts {
        from_label,
        to_label,
        category,
        scope,
        retained_text,
        feedback_available,
        learn_more_url,
        first_time_prefix,
        switched_to_line,
    } = facts;
    let prefix = first_time_prefix.map(str::to_owned).unwrap_or_else(|| match category {
        Some("cyber") => format!(
            "{from_label}'s safeguards flagged this message. Our intentionally broad safeguards allow us to deliver more capabilities faster, but can sometimes flag legitimate coding and cybersecurity tasks."
        ),
        Some("bio") => format!(
            "{from_label}'s safeguards flagged this message. Our intentionally broad safeguards allow us to deliver more capabilities faster, but can sometimes flag legitimate biology tasks."
        ),
        _ => format!(
            "{from_label}'s safeguards flagged this message. This sometimes happens with safe, normal conversations."
        ),
    });
    let body = match scope {
        lingxi_core::host::refusal_server_control::BannerScope::Session => switched_to_line
            .map(str::to_owned)
            .unwrap_or_else(|| format!("Switched to {to_label}.")),
        lingxi_core::host::refusal_server_control::BannerScope::Local => {
            let completion = if retained_text.is_empty() {
                format!("generated by {to_label} instead")
            } else {
                format!("completed by {to_label}")
            };
            format!("This response was {completion}. Your session model is unchanged.")
        }
    };
    let feedback = if feedback_available {
        format!("Send feedback with /feedback or learn more: {learn_more_url}")
    } else {
        format!("You can learn more: {learn_more_url}")
    };
    let details = category
        .map(sanitize_server_fallback_category)
        .filter(|category| !category.is_empty())
        .map_or_else(String::new, |category| {
            format!("\n\nDetails: `[{category}]`")
        });
    format!("{prefix} {body} {feedback}{details}")
}

fn sanitize_server_fallback_category(value: &str) -> String {
    static STRIP_RUNS: OnceLock<Regex> = OnceLock::new();
    static DROP_BRACKETS: OnceLock<Regex> = OnceLock::new();
    let strip_runs = STRIP_RUNS.get_or_init(|| {
        Regex::new(
            r"[\p{Cc}\p{Cf}\p{Co}\p{Cn}\p{Default_Ignorable_Code_Point}\x{2028}\x{2029}\x{2800}]+",
        )
        .expect("Unicode category sanitizer regex is valid")
    });
    let drop_brackets = DROP_BRACKETS.get_or_init(|| {
        Regex::new(r"[`\[\]]").expect("category punctuation sanitizer regex is valid")
    });

    // Native k1e first removes ANSI escapes, replaces each unsafe Unicode
    // run with a space, then strips details delimiters before collapsing
    // whitespace. The SDK event is a Rust `str`, so the native `Cs` class has
    // no representable values to match here.
    let without_ansi = lingxi_core::host::display::strip_ansi_text(value);
    let with_spaces = strip_runs.replace_all(&without_ansi, " ");
    let without_brackets = drop_brackets.replace_all(&with_spaces, "");
    let collapsed = without_brackets
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ");

    let mut result = String::new();
    let mut used = 0;
    for ch in collapsed.trim().chars() {
        let units = ch.len_utf16();
        if used + units > 255 {
            break;
        }
        used += units;
        result.push(ch);
    }
    result.trim().to_owned()
}

pub(crate) fn server_fallback_notice_content(
    orch: &crate::ConversationOrchestrator,
    transition: &ServerFallbackTransition,
    scope: lingxi_core::host::refusal_server_control::BannerScope,
    retained_text: &str,
    category: Option<&str>,
) -> String {
    let from_label = server_fallback_display_name(orch, &transition.from);
    let to_label = server_fallback_display_name(orch, &transition.to);
    let learn_more_url = server_fallback_help_url(&transition.from.model);

    // This adapter has no host snapshot for native `Fo`, `QA/Hre`, `_I`,
    // `T$r`, or the complete `_w` model classifier. It uses current model
    // labels and the generic copy only; the pure renderer accepts those
    // explicit facts when composition provides them. Do not infer feedback
    // availability from `interactive_session` or TTY state.
    server_fallback_notice_text(ServerFallbackNoticeFacts {
        from_label: &from_label,
        to_label: &to_label,
        category,
        scope,
        retained_text,
        // Current composition does not yet expose the native
        // allow_product_feedback resolver to this controller.
        feedback_available: false,
        learn_more_url,
        first_time_prefix: None,
        switched_to_line: None,
    })
}

fn server_fallback_display_name(
    orch: &crate::ConversationOrchestrator,
    route: &ModelRoute,
) -> String {
    if let Some(name) = crate::prompt::env_meta::marketing_name_for_model(&route.model) {
        return name.to_owned();
    }
    orch.api
        .list_model_listings()
        .into_iter()
        .find(|listing| {
            lingxi_core::host::refusal_state::wire_identity(&listing.request_model)
                == lingxi_core::host::refusal_state::wire_identity(&route.model)
                && route
                    .profile
                    .as_ref()
                    .is_none_or(|profile| listing.provider_id == *profile)
        })
        .map_or_else(|| route.model.clone(), |listing| listing.display_model)
}

fn server_fallback_help_url(model: &str) -> &'static str {
    // This covers the canonical Opus/Fable IDs and the configured default
    // Fable model. Native `_w` also recognizes a larger alias resolver that
    // is not currently exposed to this controller.
    let canonical = lingxi_core::host::model_capabilities::normalize_model_id(model);
    if canonical == "claude-opus-5" {
        return "https://support.claude.com/en/articles/16049681";
    }
    let is_fable = canonical.starts_with("claude-fable-")
        || matches!(canonical.as_str(), "fable" | "fable[1m]")
        || std::env::var("ANTHROPIC_DEFAULT_FABLE_MODEL")
            .ok()
            .is_some_and(|default| {
                lingxi_core::host::model_capabilities::normalize_model_id(&default) == canonical
            });
    if is_fable {
        "https://support.claude.com/en/articles/15363606"
    } else {
        "https://support.claude.com/en/articles/8106465"
    }
}

tokio::task_local! { pub(crate) static ROUTE: Option<ModelRoute>; }

pub(crate) fn current() -> Option<ModelRoute> {
    ROUTE.try_with(Clone::clone).ok().flatten()
}

pub(crate) async fn fallback_target_context(
    orch: &crate::ConversationOrchestrator,
    user_model: &str,
    chain_step_model: Option<&str>,
) -> lingxi_core::host::refusal_driver::FallbackTargetContext {
    let target = orch
        .model_runtime
        .refusal_cascade
        .lock()
        .await
        .target_model()
        .map(str::to_owned);
    let selection = orch
        .model_runtime
        .refusal_selection
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
        .clone();
    let server_query = crate::server_fallback::query_state();
    let server_fallback = orch.config.server_refusal_fallback.as_ref().map(|policy| {
        let model = chain_step_model.unwrap_or(user_model);
        let disabled = lingxi_core::host::refusal_server::disabled_by_environment(
            std::env::var(branding::DISABLE_REFUSAL_FALLBACK_ENV)
                .ok()
                .as_deref(),
        );
        let mut policy = policy.clone();
        policy.enabled &= !disabled;
        policy.candidate_same_model = policy.candidate_model.as_deref().is_some_and(|candidate| {
            lingxi_core::host::refusal_state::wire_identity(candidate)
                == lingxi_core::host::refusal_state::wire_identity(model)
        });
        lingxi_core::host::refusal_server::QueryPolicy {
            model: model.into(),
            query: lingxi_core::host::refusal_server::Query {
                already_used: server_query.fallback_count >= 2,
                declined: policy.declined || server_query.declined,
                in_cascade_episode: target.is_some(),
                cascade_next: target.clone(),
                is_main_thread: true,
                suppression_already_logged: false,
            },
            policy,
        }
    });
    lingxi_core::host::refusal_driver::FallbackTargetContext {
        server_fallback,
        user_model: user_model.into(),
        turn_override: target.clone(),
        chain_step_model: chain_step_model.map(str::to_owned),
        latched_model: selection
            .live_latch()
            .map(|latch| latch.fallback_model.clone()),
        main_loop_override: Some(orch.session.lock().await.model.clone()),
        refusal_header_armed: selection.header_armed,
        refusal_occurred: selection.refusal_occurred,
        refusal_lane_enabled: false,
        refusal_origin_request_id: selection.origin_request_id,
    }
}

pub(crate) fn restore_refusal_selection(
    orch: &crate::ConversationOrchestrator,
    requested_model: Option<&str>,
    history: &[lingxi_core::types::ConversationMessage],
    fork: bool,
) -> bool {
    let frames = lingxi_core::host::refusal_state::frames(history);
    let mut selection = orch
        .model_runtime
        .refusal_selection
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let Some(model) = requested_model else {
        selection.restore_headers(&frames, fork);
        return false;
    };
    let identity = lingxi_core::host::refusal_state::wire_identity;
    let restored = selection.restore(
        model,
        &frames,
        fork,
        Some(Some(orch.config.model.clone())),
        |left, right| {
            identity(left) == identity(right)
                || llm_runtime::model::thinking::canonical(left)
                    == llm_runtime::model::thinking::canonical(right)
        },
        |left, right| identity(left) == identity(right),
    );
    if restored {
        if let Some(latch) = selection
            .latch
            .as_mut()
            .filter(|latch| latch.fallback_model == model)
        {
            // Native cCe restores the host-selected launch model, not any
            // notice's originalModel. The profile extension is per-hop, so it
            // is safe to restore only when the latest notice's originalModel
            // is that already-selected launch route. A later B→C notice may
            // carry the old A profile after A→B, but without a restore-model
            // field the host cannot prove that profile still belongs to A.
            let restored_model = latch
                .previous_app_state_model
                .as_ref()
                .and_then(Option::as_deref);
            if let Some(frame) = frames.last().filter(|frame| {
                frame.neutralized_by_fork != Some(true)
                    && frame.previous_profile.is_some()
                    && restored_model.is_some_and(|restored_model| {
                        identity(&frame.original_model) == identity(restored_model)
                    })
            }) {
                latch.previous_profile = frame
                    .previous_profile
                    .as_ref()
                    .expect("filtered profile snapshot")
                    .clone();
            }
        }
    }
    restored
}

/// Return only the provider-profile extension for an already-selected model.
/// Native cold resume chooses the model from the last assistant row; a server
/// notice by itself is never model-selection evidence.
pub(crate) fn server_session_serving_profile(
    history: &[lingxi_core::types::ConversationMessage],
    selected_model: &str,
) -> Option<Option<String>> {
    let identity = lingxi_core::host::refusal_state::wire_identity;
    let frame = lingxi_core::host::refusal_state::frames(history)
        .into_iter()
        .last()?;
    if frame.serving_profile.is_none()
        || frame.neutralized_by_fork == Some(true)
        || identity(&frame.fallback_model) != identity(selected_model)
    {
        return None;
    }
    Some(frame.serving_profile.expect("checked above"))
}

pub(crate) fn server_fallback_matches_model(
    history: &[lingxi_core::types::ConversationMessage],
    selected_model: &str,
) -> bool {
    let identity = lingxi_core::host::refusal_state::wire_identity;
    lingxi_core::host::refusal_state::frames(history)
        .into_iter()
        .last()
        .is_some_and(|frame| {
            frame.neutralized_by_fork != Some(true)
                && identity(&frame.fallback_model) == identity(selected_model)
        })
}

pub(crate) fn configured_chain(raw: &str, primary: &str) -> Vec<String> {
    let llm_runtime::FallbackPolicy::Models(models) =
        llm_runtime::FallbackPolicy::from_models_csv(raw)
    else {
        unreachable!("CSV parses an explicit model list")
    };
    models
        .into_iter()
        .filter(|model| model != primary)
        .collect()
}

/// Current native `ll`, with no availability substitution for an explicit
/// configured chain. Equal entries are skipped, except for its last in-place
/// retry on overload/server failure. The caller owns the next chain index.
pub(crate) fn advance<'a>(
    chain: &'a [String],
    from: usize,
    failed: &'a str,
    reason: &str,
) -> (usize, Option<&'a str>) {
    let mut index = from;
    let mut saw_failed = false;
    while let Some(model) = chain.get(index) {
        if model == failed {
            saw_failed = true;
        } else {
            return (index, Some(model));
        }
        index += 1;
    }
    (
        index,
        (saw_failed && matches!(reason, "overloaded" | "server_error")).then_some(failed),
    )
}

pub(crate) fn resolve(
    reference: &str,
    current: &ModelRoute,
    listings: &[ModelListing],
) -> ModelRoute {
    let (model, explicit_profile) = parse_model_ref(reference, listings);
    // A bare model keeps the serving profile when that profile offers it;
    // otherwise normal SDK routing selects the model's provider. Qualified
    // references preserve the explicit provider, including slash-bearing IDs.
    let profile = explicit_profile.or_else(|| {
        current
            .profile
            .as_ref()
            .filter(|profile| {
                listings.iter().any(|listing| {
                    listing.request_model == model && listing.provider_id == **profile
                })
            })
            .cloned()
    });
    ModelRoute { model, profile }
}

pub(crate) fn server_error_notice(
    from: &str,
    to: &str,
    from_window: u64,
    to_window: u64,
) -> String {
    let mut content = format!("Switched to {to} due to high demand for {from}");
    if to_window < from_window {
        content.push_str(&format!(
            " · context window {} → {} tokens",
            format_window(from_window),
            format_window(to_window)
        ));
    }
    content
}

// Native Ho/gr/vs: en-US Intl compact, one fractional digit, remove .0,
// upper-case. Integer arithmetic keeps Intl's half-expand rounding exact.
fn format_window(tokens: u64) -> String {
    if tokens < 1000 {
        return tokens.to_string();
    }
    let units = [
        (1000u64, "K"),
        (1_000_000, "M"),
        (1_000_000_000, "B"),
        (1_000_000_000_000, "T"),
    ];
    for (index, (scale, suffix)) in units.iter().enumerate() {
        let tenths = (u128::from(tokens) * 10 + u128::from(*scale) / 2) / u128::from(*scale);
        if tenths >= 10_000 && index + 1 < units.len() {
            continue;
        }
        let whole = tenths / 10;
        return if tenths % 10 == 0 {
            format!("{whole}{suffix}")
        } else {
            format!("{whole}.{}{suffix}", tenths % 10)
        };
    }
    unreachable!("compact formatter always accepts its final unit")
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn current_native_chain_and_server_notice_cases() {
        let fixture: serde_json::Value = serde_json::from_str(include_str!(
            "../tests/fixtures/model_fallback_2_1_288.json"
        ))
        .unwrap();
        for case in fixture["configuredCases"].as_array().unwrap() {
            assert_eq!(
                serde_json::to_value(configured_chain(
                    case["fallback"].as_str().unwrap(),
                    case["primary"].as_str().unwrap()
                ))
                .unwrap(),
                case["expected"],
                "{case}"
            );
        }
        for case in fixture["chainCases"].as_array().unwrap() {
            let chain: Vec<String> = serde_json::from_value(case["chain"].clone()).unwrap();
            let (index, target) = advance(
                &chain,
                case["from"].as_u64().unwrap() as usize,
                case["failed"].as_str().unwrap(),
                case["reason"].as_str().unwrap(),
            );
            assert_eq!(
                serde_json::json!({"index":index,"target":target}),
                case["expected"],
                "{case}"
            );
        }
        for case in fixture["noticeCases"].as_array().unwrap() {
            assert_eq!(
                server_error_notice(
                    case["from"].as_str().unwrap(),
                    case["to"].as_str().unwrap(),
                    case["from_window"].as_u64().unwrap(),
                    case["to_window"].as_u64().unwrap()
                ),
                case["expected"].as_str().unwrap(),
                "{case}"
            );
        }
    }
}
