//! Native .286 AutoMem `fJ`: normalize line breaks, strip invisible/control
//! code points, then neutralize only the native memory framing tags.
//! Tables are generated by `instruction_announcements_286_oracle.mjs` from the
//! pinned native J8e / iu / Au helpers; this uses no broader subagent guard.

use fancy_regex::{Regex, RegexBuilder};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::sync::LazyLock;

#[derive(Deserialize)]
struct Tables {
    exclusions: Vec<[u32; 2]>,
    reading: Vec<(u32, String)>,
    patterns: Vec<String>,
}

static TABLES: LazyLock<Tables> = LazyLock::new(|| {
    serde_json::from_str(include_str!("instruction_memory_sanitize_286.json"))
        .expect("pinned native memory sanitizer tables")
});

const JS_SPACE_CLASS: &str =
    r"\x09-\x0d\x20\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff";

static PATTERNS: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    TABLES
        .patterns
        .iter()
        .map(|pattern| compile_native_tag_pattern(pattern))
        .collect()
});

pub(crate) fn compile_native_tag_pattern(pattern: &str) -> Regex {
    // These occurrences of JS \s and \w are inside character classes.
    let pattern = pattern
        .replace(r"\s", JS_SPACE_CLASS)
        .replace(r"\w", "A-Za-z0-9_");
    RegexBuilder::new(&pattern)
        .case_insensitive(true)
        .delegate_size_limit(32 * 1024 * 1024)
        .backtrack_limit(usize::MAX)
        .build()
        .expect("pinned native tag recognizer")
}

/// ECMAScript String.prototype.trim, including BOM and excluding NEL.
#[must_use]
pub fn js_trim(text: &str) -> &str {
    text.trim_matches(|character| {
        matches!(character,
            '\u{0009}'..='\u{000d}' | '\u{0020}' | '\u{00a0}' | '\u{1680}' |
            '\u{2000}'..='\u{200a}' | '\u{2028}' | '\u{2029}' | '\u{202f}' |
            '\u{205f}' | '\u{3000}' | '\u{feff}'
        )
    })
}

fn excluded(character: char) -> bool {
    let codepoint = u32::from(character);
    let index = TABLES
        .exclusions
        .partition_point(|range| range[1] < codepoint);
    TABLES
        .exclusions
        .get(index)
        .is_some_and(|range| range[0] <= codepoint)
}

/// The AutoMem-only transformation performed before the renderer's JS trim.
#[must_use]
pub fn sanitize_memory_body(text: &str) -> String {
    let mut cleaned = String::with_capacity(text.len());
    let mut characters = text.chars().peekable();
    while let Some(character) = characters.next() {
        let character = match character {
            '\r' => {
                if characters.peek() == Some(&'\n') {
                    characters.next();
                }
                '\n'
            }
            '\u{2028}' | '\u{2029}' => '\n',
            other => other,
        };
        if !excluded(character) {
            cleaned.push(character);
        }
    }
    let openers = native_tag_opener_offsets(&cleaned, &PATTERNS);
    let mut result = String::with_capacity(cleaned.len() + openers.len());
    let mut copied = 0;
    for opener in openers {
        result.push_str(&cleaned[copied..opener]);
        result.push_str("<\\");
        copied = opener
            + cleaned[opener..]
                .chars()
                .next()
                .expect("matched opener")
                .len_utf8();
    }
    result.push_str(&cleaned[copied..]);
    result
}

/// Shared native `Eu`/`M` reading and original-offset projection. This does not
/// perform AutoMem's newline normalization or invisible-character removal.
pub(crate) fn native_tag_opener_offsets(text: &str, patterns: &[Regex]) -> BTreeSet<usize> {
    let mut reading = String::with_capacity(text.len());
    let mut offsets = Vec::new();
    for (original, character) in text.char_indices() {
        let replacement = TABLES
            .reading
            .binary_search_by_key(&u32::from(character), |entry| entry.0)
            .ok()
            .map(|index| TABLES.reading[index].1.as_str());
        if let Some(replacement) = replacement {
            for character in replacement.chars() {
                offsets.push((reading.len(), original));
                reading.push(character);
            }
        } else {
            offsets.push((reading.len(), original));
            reading.push(character);
        }
    }
    let mut openers = BTreeSet::new();
    for pattern in patterns {
        for found in pattern.find_iter(&reading) {
            let found = found.expect("native tag recognizer match");
            let index = offsets
                .binary_search_by_key(&found.start(), |entry| entry.0)
                .expect("recognizer matches a Unicode character boundary");
            openers.insert(offsets[index].1);
        }
    }
    openers
}
